shortyuv: Fix compile warnings/errors due to comparing signed and unsigned integers.
GCC 4.8.0 Linux64:

source/encoder/TShortYUV.cpp:424:32: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    for(int x = 0; x < iWidth; x++)